[[plugins]]
repo    = 'Shougo/dein.vim'

[[plugins]]
repo    = 'w0ng/vim-hybrid'

[[plugins]]
repo    = 'junegunn/vim-easy-align'
hook_add = '''
	vmap <Enter> <Plug>(EasyAlign)
	nmap ga <Plug>(EasyAlign)
'''

[[plugins]]
repo    = 'rking/ag.vim'

[[plugins]]
repo    = 'ctrlpvim/ctrlp.vim'
hook_add = '''
	let g:ctrlp_user_command = 'ag -l --nocolor -g "" %s'
'''

[[plugins]]
repo    = 'tpope/vim-surround'

[[plugins]]
repo    = 'jiangmiao/auto-pairs'

[[plugins]] # タブごとにカレントディレクトリを管理
repo = 'kana/vim-tabpagecd'

[[plugins]] # ターミナル版vimの背景をターミナルと同じにする
repo = 'miyakogi/seiya.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
