[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
hook_add = '''
  let g:vim_markdown_folding_disabled = 1
'''

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'cd app && yarn install'
hook_add = '''
    let vim_markdown_preview_github=1
'''

[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['html', 'vue']
hook_source = '''
    let g:closetag_filenames = '*.html,*.vue'
'''


[[plugins]]
repo = 'turbio/bracey.vim'
on_ft = ['html']
build = 'npm install --prefix server'

[[plugins]]
repo = 'tweekmonster/braceless.vim'
on_ft = ['python', 'yaml']

[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = ['go']
