[[plugins]]
repo    = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]] repo    = 'tomasr/molokai'

[[plugins]]
repo    = 'w0ng/vim-hybrid'

[[plugins]]
repo    = 'djjcast/mirodark'

[[plugins]]
repo    = 'vim-scripts/Zenburn'

[[plugins]]
repo    = 'junegunn/vim-easy-align'
hook_add = '''
	vmap <Enter> <Plug>(EasyAlign)
	nmap ga <Plug>(EasyAlign)
'''

[[plugins]]
repo    = 'rking/ag.vim'

[[plugins]]
repo    = 'ctrlpvim/ctrlp.vim'
hook_add = '''
	let g:ctrlp_user_command = 'ag -l --nocolor -g "" %s'
'''

[[plugins]] #changes status line
repo    = 'bling/vim-airline'

[[plugins]]
repo    = 'tpope/vim-surround'

[[plugins]]
repo    = 'jiangmiao/auto-pairs'

[[plugins]] # タブごとにカレントディレクトリを管理
repo = 'kana/vim-tabpagecd'

[[plugins]] # gitをvimから操作できるようにする。
repo = 'tpope/vim-fugitive'

[[plugins]] # ターミナル版vimの背景をターミナルと同じにする
repo = 'miyakogi/seiya.vim'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'Chiel92/vim-autoformat'

[[plugins]]
repo = 'vim-syntastic/syntastic'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
	let g:ale_linters = { 'jsx': ['eslint'] }
'''
