[[plugins]]
repo    = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo    = 'tomasr/molokai'

[[plugins]]
repo    = 'w0ng/vim-hybrid'

[[plugins]]
repo    = 'djjcast/mirodark'

[[plugins]]
repo    = 'vim-scripts/Zenburn'

[[plugins]]
repo    = 'Shougo/vimfiler'
depends = 'unite.vim'

[[plugins]]
repo    = 'junegunn/vim-easy-align'

[[plugins]]
repo    = 'rking/ag.vim'

[[plugins]]
repo    = 'ctrlpvim/ctrlp.vim'

[[plugins]] #changes status line
repo    = 'bling/vim-airline'

[[plugins]]
repo    = 'tpope/vim-surround'

[[plugins]]
repo    = 'jiangmiao/auto-pairs'

[[plugins]] # タブごとにカレントディレクトリを管理
repo = 'kana/vim-tabpagecd'

[[plugins]] # gitをvimから操作できるようにする。
repo = 'tpope/vim-fugitive'

[[plugins]] # ターミナル版vimの背景をターミナルと同じにする
repo = 'miyakogi/seiya.vim'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'Chiel92/vim-autoformat'

[[plugins]]
repo = 'vim-syntastic/syntastic'

[[plugins]]
repo = 'neomake/neomake'
hook_add = '''
	autocmd! BufWritePost * Neomake
'''
hook_source = '''
	let g:noemake_javascript_enabled_makers = ['eslint']
	let g:neomake_error_sign = {'text': '>>', 'texthl': 'Error'}
	let g:neomake_warning_sign = {'text': '>>',  'texthl': 'Todo'}
'''

[[plugins]]
repo = 'benjie/neomake-local-eslint.vim'
