[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = "Shougo/deoplete.nvim"
hook_source = """
  let g:deoplete#enable_at_startup = 1
"""

[[plugins]]
repo = "Robzz/deoplete-omnisharp"
on_source = ["deoplete.nvim"]

[[plugins]]
repo = 'neovimhaskell/haskell-vim'
on_ft = ['haskell']

[[plugins]]
repo = 'leafgarland/typescript-vim' 
on_ft = ['typescript']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']


[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'cd app & yarn install'

[[plugins]]
repo = 'OmniSharp/omnisharp-vim'
on_ft = ['cs', 'csi', 'csx']
hook_add = '''
  let g:OmniSharp_server_stdio = 1
  let g:OmniSharp_selector_ui = 'fzf'
'''

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
