[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
	vmap <Enter> <Plug>(EasyAlign)
	nmap ga <Plug>(EasyAlign)
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
	let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]] # タブごとにカレントディレクトリを管理
repo = 'kana/vim-tabpagecd'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  source ~/.config/nvim/plugins/ale.rc.vim
'''

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
on_ft = ['haskell', 'javascript', 'typescript']
depends = 'deoplete.nvim'
build = 'bash install.sh'
hook_add = '''
  source ~/.config/nvim/plugins/LanguageClient-neovim.rc.vim
'''
hook_post_source = '''
  set omnifunc=LanguageClient#complete
'''

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]] # vimのテキストをシンタックスハイライト付きでコピーする
repo = 'zerowidth/vim-copy-as-rtf'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  let g:gitgutter_sign_added = '.'
  let g:gitgutter_sign_modified = '.'
  let g:gitgutter_sign_removed = '.'
  let g:gitgutter_sign_removed_first_line = '.'
  let g:gitgutter_sign_modified_removed = '.'
'''
