[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
	vmap <Enter> <Plug>(EasyAlign)
	nmap ga <Plug>(EasyAlign)
'''

[[plugins]] # カッコの補完
repo = "cohama/lexima.vim"

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]] # タブごとにカレントディレクトリを管理
repo = 'kana/vim-tabpagecd'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  set signcolumn=yes
  set updatetime=250
  let g:gitgutter_sign_added = '+'
  let g:gitgutter_sign_modified = '~'
  let g:gitgutter_sign_removed = '-'
  let g:gitgutter_sign_removed_first_line = '.'
  let g:gitgutter_sign_modified_removed = '.'
'''

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-speeddating'

# [[plugins]]
# repo = 'scrooloose/nerdtree'
# hook_add = '''
#   let g:NERDTreeWinSize = 50
#   nnoremap <silent><C-e> :NERDTreeToggle<CR>
# '''

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
    let g:fzf_layout = { 'down': '~60%' }
    nnoremap <silent><C-p> :Files<CR>
    nnoremap <silent><leader>g :Ag<CR> 
    command! -bang -nargs=? -complete=dir Files
      \ call fzf#vim#files(<q-args>, fzf#vim#with_preview({'source': 'ag -S -l ""'}), <bang>0)

    command! -bang -nargs=* Ag
      \ call fzf#vim#ag(<q-args>, fzf#vim#with_preview('right:50%'), <bang>0)
'''

[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
  nmap n <Plug>(anzu-n-with-echo)
  nmap N <Plug>(anzu-N-with-echo)
  nmap * <Plug>(anzu-star-with-echo)
  nmap # <Plug>(anzu-sharp-with-echo)
'''

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
  " let g:airline_theme = 'iceberg'
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'

[[plugins]]
repo = 'neoclide/coc.nvim'
merge = 0
build = './install.sh nightly'
hook_add = '''
  source ~/.config/nvim/plugins/coc.rc.vim
'''

[[plugins]]
repo = 'gre/play2vim'

[[plugins]]
repo = 'tpope/vim-commentary'


# カラースキーム
[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'AlessandroYorba/Alduin'

[[plugins]]
repo = 'sainnhe/gruvbox-material'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
    " <Leader>f{char} to move to {char}
    map  <Leader>f <Plug>(easymotion-bd-f)
    nmap <Leader>f <Plug>(easymotion-overwin-f)

    " s{char}{char} to move to {char}{char}
    nmap <leader>s <Plug>(easymotion-overwin-f2)

    " Move to line
    map <Leader>l <Plug>(easymotion-bd-jk)
    " nmap <Leader>l <Plug>(easymotion-overwin-line)

    " Move to word
    map  <Leader>w <Plug>(easymotion-bd-w)
    nmap <Leader>w <Plug>(easymotion-overwin-w)

    " nmap <leader>s <Plug>(easymotion-prefix)
    " nmap <leader>s <Plug>(easymotion-s)
    " nmap <leader>w <Plug>(easymotion-bd-w)
    " nmap <leader>j <Plug>(easymotion-j)
    " nmap <leader>k <Plug>(easymotion-k)
    " map  <Leader>f <Plug>(easymotion-bd-f)
    " nmap <Leader>f <Plug>(easymotion-overwin-f)
    " " Move to line
    " map <leader>l <Plug>(easymotion-bd-jk)
    " nmap <leader>l <Plug>(easymotion-overwin-line)
    " let g:EasyMotion_smartcase = 1
    " let g:EasyMotion_use_migemo = 1
'''


# defx.nvim (ファイラー) 関連
[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-icons', 'defx-git']
hook_add = '''
  source ~/.config/nvim/plugins/defx.rc.vim
'''

[[plugin]]
repo = 'tpope/vim-commentary'
